### ISSUE TITLE
Process

### ISSUE THREAD

**Issue by kito99** [cincheo/jsweet-candy-js-quickstart#2]
So, to be clear, you have to manually write Java classes that expose the interfaces for the JS code you want to expose? Is there any way to automate this process?

**Comment by kito99** [comment]
Oh, nevermind; I see I can just use this: http://www.jsweet.org/online-typescript-to-java-api-translator/

**Comment by renaudpawlak** [comment]
Yep. The online api translator is a partial exposure of the translation engine we use internally to produce our own candies (the ones here: http://www.jsweet.org/candies-snapshots/). The online translator may not produce fully compilable code, but it is a good start to have a first version and polish it manually, and of course create a candy out of it using this starter project. I am pretty sure that there is room for improvement, so don't hesitate to report about it and share your thoughts about the process.

@kito99 how is your JavaOne presentation doing? Do you think it would be a good idea to advertise your talk to some friends that would be in JavaOne?

**Comment by kito99** [comment]
Thanks, @renaudpawlak. I've got a lot of work left to do for the presentation, and the jsweet portion is highly dependent on my ability to get primeng working. So although things are looking good for doing the front-end in jsweet instead of pure TypeScript, I've got a little more work to do before I know for sure.
